# Application Configuration
spring:
  application:
    name: homework

logging:
  level:
    me:
      vladislav:
        homework: INFO

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: shutdown
      base-path: /admin/actuator/
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    use-root-path: true  # Wow, it's nice :)
    operationsSorter: method
    tagsSorter: alpha
