CREATE TABLE books
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    author VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    author      VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    duration    INTEGER,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE universities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    city          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255),
    rate_krutosty INTEGER                                 NOT NULL,
    CONSTRAINT pk_universities PRIMARY KEY (id)
);

CREATE TABLE user_book
(
    book_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

CREATE TABLE user_course
(
    course_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT pk_user_course PRIMARY KEY (course_id, user_id)
);

CREATE TABLE user_university
(
    university_id BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    CONSTRAINT pk_user_university PRIMARY KEY (university_id, user_id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE user_course
    ADD CONSTRAINT fk_usecou_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE user_course
    ADD CONSTRAINT fk_usecou_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_book
    ADD CONSTRAINT fk_user_book_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE user_book
    ADD CONSTRAINT fk_user_book_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_university
    ADD CONSTRAINT fk_useuni_on_university FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE user_university
    ADD CONSTRAINT fk_useuni_on_user FOREIGN KEY (user_id) REFERENCES users (id);
