CREATE TABLE books
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255)                            NOT NULL,
    author  VARCHAR(255)                            NOT NULL,
    user_id BIGINT,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    author      VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    duration    INTEGER,
    user_id     BIGINT,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE universities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    city          VARCHAR(255)                            NOT NULL,
    description   VARCHAR(255),
    rate_krutosty INTEGER                                 NOT NULL,
    user_id       BIGINT,
    CONSTRAINT pk_universities PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT FK_BOOKS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE universities
    ADD CONSTRAINT FK_UNIVERSITIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);